imports:
  - { resource: registries.yaml }

services: &services
  _defaults: &defaults
    autowire: true
    autoconfigure: true
  
  FRZB\Component\MetricsPower\:
    resource: '../../{Action,EventListener,Handler,Factory,TypeExtractor,Logger,OptionsResolver,Processor}'
    exclude: '../../**/{Attribute,Configuration,Data,DependencyInjection,Enum,Exception,Helper,Tests,Traits}'

when@test:
  services:
    <<: *services
    _defaults:
      <<: *defaults
      public: true
